### ISSUE TITLE
Plugin already registered under a different name: sysstats-processes=None

### ISSUE THREAD

**Issue by mtelka** [saltstack/pytest-system-statistics#4]
I'm trying to run tests for `pytest-system-statistics 1.0.2` using `pytest 8.1.1` and the testing fails with the following error:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/_pytest/main.py", line 283, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/_hooks.py", line 501, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/_manager.py", line 119, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/_callers.py", line 138, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/_callers.py", line 121, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/_pytest/logging.py", line 785, in pytest_sessionstart
INTERNALERROR>     return (yield)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/_callers.py", line 102, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "$(BUILD_DIR)/src/pytestsysstats/plugin.py", line 237, in pytest_sessionstart
INTERNALERROR>     session.config.pluginmanager.register(stats_processes_instance, "sysstats-processes")
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/_pytest/config/__init__.py", line 499, in register
INTERNALERROR>     plugin_name = super().register(plugin, name)
INTERNALERROR>   File "/usr/lib/python3.9/vendor-packages/pluggy/_manager.py", line 145, in register
INTERNALERROR>     raise ValueError(
INTERNALERROR> ValueError: Plugin already registered under a different name: sysstats-processes=None
```

**Comment by mtelka** [comment]
I'm not longer able to reproduce this with `pytest 8.3.1`.
